CREATE TABLE fin_coins (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  name text,
  symbol text,
  coingecko_id text,
  
  unique(symbol)
);

alter table fin_coins enable row level security;

create policy "Public fin_coins are viewable by everyone."
  on fin_coins for select
  using ( true );

CREATE TABLE fin_portfolios (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,

  name text,
  user_id text,

  data jsonb,

  cached_data jsonb
);

CREATE TABLE fin_portfolio_transactions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,

  portfolio_id bigint,
  coin_id bigint,
  user_id text,

  type int default 1 not null,

  quantity int not null,
  price_per_coin decimal(10,4) not null,

  inserted_at timestamp with time zone not null,

  data jsonb,

  cached_data jsonb
);
